version: "3.9"
services:
  app:
    build:
      context: ../..
      dockerfile: ./deployments/docker/Dockerfile
    ports:
      - 4936:4936
    depends_on:
      - postgres
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./data/logs:/app/logs
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mimo
      TZ: Asia/Shanghai
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
