# TODO 配置待调试

version: '3.9'
services:
  app:
    build: .
    ports:
      - "4936:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
