FROM golang AS build
WORKDIR /app

RUN go install github.com/go-task/task/v3/cmd/task@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
COPY taskfile.yml .
RUN task install

COPY . .
RUN task docs
RUN task build:alpine

FROM alpine:latest
WORKDIR /app

COPY --from=build /app/config/app.yaml ./config/
COPY --from=build /app/target/main ./app

CMD ["./app", "-c", "./config/app.yaml"]
EXPOSE 4936
