# yaml-language-server: $schema=../config/v0.schema.json

consoleLevel: 63

cors:
  enabled: true
  allowAllOrigins: false
  allowOrigins: [http://localhost:5173]
  allowMethods: [GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS]
  allowHeaders: ["*"]
  allowCredentials: false
  maxAge: 5m

jwt:
  claims:
    audience: [http://localhost:5173]
    issuer: tsingshaner
    subject: demo
    expire: 30m
    refreshExpire: 72h
  methods:
    - alg: HS256
      key: secretwithdw
    - alg: EdDSA
      pem:
        publicPath: public.pem
        privatePath: private.pem

postgres:
  host: 127.0.0.1
  port: 5432
  user: qingshaner
  password: "123456"
  database: temp
  sslMode: prefer
  timeZone: Asia/Shanghai

server:
  host: 127.0.0.1
  port: 4936
  base: /api
  mode: release
  requestIdHeader: X-Request-ID
  readTimeout: 5m
  writeTimeout: 5m
  maxHeaderBytes: 1048576

swagger:
  enable: false
  docsBase: /docs
  version: "v1"
  server:
    title: "Api Docs"

logger:
  gorm:
    level: 63
    slowThreshold: 200ms
    ignoreRecordNotFoundError: true
    parameterizedQueries: false
  level: 63
  stdoutWriter:
    enable: false
