# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

tasks:
  default: task --list-all

  example: go run ./example/main.go --config config.example.yml
