# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

interval: 500ms

vars:
  APP_NAME: server

tasks:
  migrate: atlas migrate diff --env gorm
  migrate:apply:
    cmd: atlas migrate apply --env gorm --dir file://./migrations {{.CLI_ARGS}}

  build:
    cmd: go build -o target/{{.APP_NAME}}{{exeExt}} server/main.go
    desc: Build the server for local machine
    deps: [swag]
    sources:
      - ./server/main.go
      - ../api/openapi/docs.go
      - ../app/*.go
      - ../config/*
      - ../mod/**/*.go

  start:
    desc: Start server app
    deps: [build]
    cmds:
      - ./target/{{.APP_NAME}}{{exeExt}} --config ../config/config.example.yml  {{.CLI_ARGS}}

  start:dev:
    desc: Start the server and restart when files changed
    deps: [build]
    watch: true
    cmds:
      - task kill
      - task start -- --silence | prettylog
    env: { FORCE_COLOR: 1 }
    method: none
    run: always
    sources:
      - cmd/server/main.go
      - ../app/**/*.go
      - ../mod/**/*.go
      - ../config/*

  swag:
    desc: Generate swagger docs
    vars:
      CLI_PATH_ARGS: -d ../app,../mod/user -g ../app/app.go -o ../api/openapi --md ../api/md
      CLI_FLAG_ARGS: --parseDependency --parseInternal
    cmd: swag init {{.CLI_PATH_ARGS}} {{.CLI_FLAG_ARGS}}
    sources:
      - ../api/md/*
      - ../app/app.go
      - ../config/*.yml
      - ../mod/*/internal/handler/*.go
      - ../swagger/*.go

  kill:
    desc: Kill the running server
    ignore_error: true
    silent: true
    cmds:
      - cmd: "taskkill /IM {{.APP_NAME}}.exe /F"
        platforms: [windows]
      - cmd: pkill -f "{{.APP_NAME}}"
        platforms: [linux, darwin]

  secret:
    desc: Generate jwt ed25519 key pair
    cmds:
      - openssl genpkey -algorithm ed25519 -out private.pem
      - openssl.exe pkey -in private.pem -pubout -out public.pem
