name: open-api

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Install task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install Dependencies
        run: task install

      - name: Copy RSA keys
        shell: bash
        env:
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
        run: |
          echo "$RSA_PRIVATE_KEY" > ./config/private_key.pem
          echo "$RSA_PUBLIC_KEY }}" > ./config/public_key.pem

      - name: Open API
        run: task docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: api/open-api

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
