name: open-api

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Install Dependencies
        run: go mod download

      - name: Open API
        run: swag init -g ./cmd/server/main.go -o ./api/open-api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: api/open-api
