name: openapi

on:
  push:
    branches: ["main"]
    paths:
      - 'api/**'
      - 'app/**'
      - 'cmd/**'
      - 'config/**'
      - 'mod/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "go.mod"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Install Dependencies
        run: task install

      - name: Copy RSA keys
        shell: bash
        env:
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
        run: |
          echo "$RSA_PRIVATE_KEY" > ./config/private_key.pem
          echo "$RSA_PUBLIC_KEY }}" > ./config/public_key.pem

      - name: Open API
        run: task cmd:swag

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: api/openapi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
